// FIFA-ranking-based strength ratings (1–100) and flag emojis for WC 2026 teams.
// Ratings approximated from FIFA rankings circa mid-2025.

const FLAGS: Record<string, string> = {
  'Argentina': '🇦🇷',
  'France': '🇫🇷',
  'Spain': '🇪🇸',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Brazil': '🇧🇷',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Germany': '🇩🇪',
  'Italy': '🇮🇹',
  'Croatia': '🇭🇷',
  'Morocco': '🇲🇦',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Japan': '🇯🇵',
  'United States': '🇺🇸',
  'USA': '🇺🇸',
  'Mexico': '🇲🇽',
  'Canada': '🇨🇦',
  'Senegal': '🇸🇳',
  'Denmark': '🇩🇰',
  'Switzerland': '🇨🇭',
  'Serbia': '🇷🇸',
  'Australia': '🇦🇺',
  'Korea Republic': '🇰🇷',
  'South Korea': '🇰🇷',
  'Iran': '🇮🇷',
  'Poland': '🇵🇱',
  'Ecuador': '🇪🇨',
  'Tunisia': '🇹🇳',
  'Cameroon': '🇨🇲',
  'Ghana': '🇬🇭',
  'Saudi Arabia': '🇸🇦',
  'Qatar': '🇶🇦',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Nigeria': '🇳🇬',
  'Egypt': '🇪🇬',
  "Côte d'Ivoire": '🇨🇮',
  'Ivory Coast': '🇨🇮',
  'Austria': '🇦🇹',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Ukraine': '🇺🇦',
  'Turkey': '🇹🇷',
  'Türkiye': '🇹🇷',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Slovakia': '🇸🇰',
  'Venezuela': '🇻🇪',
  'Bolivia': '🇧🇴',
  'Paraguay': '🇵🇾',
  'Peru': '🇵🇪',
  'Chile': '🇨🇱',
  'Algeria': '🇩🇿',
  'Zimbabwe': '🇿🇼',
  'Tanzania': '🇹🇿',
  'Zambia': '🇿🇲',
  'Benin': '🇧🇯',
  'Mozambique': '🇲🇿',
  'South Africa': '🇿🇦',
  'Mali': '🇲🇱',
  'Iraq': '🇮🇶',
  'Jordan': '🇯🇴',
  'Uzbekistan': '🇺🇿',
  'New Zealand': '🇳🇿',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'Trinidad and Tobago': '🇹🇹',
  'Guatemala': '🇬🇹',
  'Czech Republic': '🇨🇿',
  'Ireland': '🇮🇪',
  'Greece': '🇬🇷',
  'Albania': '🇦🇱',
  'Slovenia': '🇸🇮',
  'Cuba': '🇨🇺',
  'Bahrain': '🇧🇭',
  'Kuwait': '🇰🇼',
}

const STRENGTHS: Record<string, number> = {
  'Argentina': 92,
  'France': 88,
  'Spain': 87,
  'England': 86,
  'Brazil': 85,
  'Portugal': 84,
  'Netherlands': 83,
  'Belgium': 82,
  'Germany': 81,
  'Italy': 80,
  'Croatia': 78,
  'Morocco': 77,
  'Uruguay': 77,
  'Colombia': 76,
  'Japan': 76,
  'United States': 75,
  'USA': 75,
  'Denmark': 75,
  'Switzerland': 74,
  'Mexico': 74,
  'Serbia': 74,
  'Korea Republic': 73,
  'South Korea': 73,
  'Senegal': 73,
  'Australia': 72,
  'Iran': 72,
  'Poland': 71,
  'Ecuador': 70,
  'Canada': 70,
  'Austria': 70,
  'Turkey': 70,
  'Türkiye': 70,
  'Nigeria': 69,
  "Côte d'Ivoire": 69,
  'Ivory Coast': 69,
  'Algeria': 68,
  'Egypt': 68,
  'Tunisia': 68,
  'Cameroon': 68,
  'Ukraine': 68,
  'Scotland': 68,
  'Czech Republic': 68,
  'Hungary': 67,
  'Romania': 67,
  'Slovakia': 66,
  'Ghana': 66,
  'Venezuela': 66,
  'Peru': 66,
  'Chile': 66,
  'Saudi Arabia': 65,
  'Costa Rica': 65,
  'Greece': 65,
  'Panama': 64,
  'Slovenia': 64,
  'Albania': 63,
  'Qatar': 63,
  'South Africa': 63,
  'Iraq': 63,
  'Ireland': 63,
  'Jordan': 62,
  'Uzbekistan': 62,
  'Mali': 62,
  'Honduras': 61,
  'Jamaica': 61,
  'Mozambique': 60,
  'Bolivia': 60,
  'Paraguay': 60,
  'New Zealand': 60,
  'Benin': 59,
  'Tanzania': 58,
  'Zambia': 58,
  'Zimbabwe': 57,
  'Trinidad and Tobago': 57,
  'Guatemala': 56,
  'Wales': 68,
}

export function getTeamStrength(name: string): number {
  return STRENGTHS[name] ?? 62
}

export function getTeamFlag(name: string): string {
  return FLAGS[name] ?? '🏳️'
}
